
GET http://localhost:4000/user 
###
GET http://localhost:4000/user/1121223
###
POST http://192.168.1.21:4000/user/login
Content-Type: application/json 

{
   "email":"eyad.om@gmail.com",
   "password":"eyad123"
}

### 

POST http://192.168.1.21:4000/user/verifyToken 
Content-Type: application/json 

{
   "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjpbeyJpZCI6MzAyMzY5OSwibmFtZSI6Im9zYW1hIG9tYXIgIiwiZW1haWwiOiJvc2FtYS5vbUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRmR3lZaXV1ZGhUeEF4dS80NllJWFouYmVnQXE4WVlyYWM5RzdKeUNaUjRicmd2R3gxbVVXUyIsImNpdHkiOiJNRUQiLCJpbWFnZVByb2ZpbGUiOiJzc3Nzc3MiLCJwcm9maWxlTGFuZ3VhZ2UiOiJkZGRkZGRkZCJ9XSwiaWF0IjoxNjU5MzI3NDk1LCJleHAiOjE2NTkzMjc1NTV9.AdURWvCIZGi6DqoHPUEWfYz2DkDejDDf52ZZkyYWwxU"
}

### 
POST http://192.168.1.21:4000/user/signup
Content-Type: application/json

 {
    "name":"eyad omar ",
    "email":"eyad.om@gmail.com",
    "password":"eyad123",
    "city":"MED",
    "imageProfile":"ssssss",
    "profileLanguage":"dddddddd"
 }

 

 